name: Do all the things

on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  do-it:
    runs-on: ubuntu-latest
    name: do-it
    permissions:
      contents: read
    steps:
      - name: do one thing
        id: do-thing
        uses: ntnu-ws/fantastiskaction@v1

  